apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: q1yzd7yzo-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6293e561990441bbbc9ce1988077a1792462c40b@sha256:0e9dd6fb2b2004c05fe9fef1eb1fd04c607c18a519cdab6bc4175217523b4246
          name: container-image
